---
- name: install apache &upload web page
  hosts: prod
  become: true

  vars:
    source_folder: '/home/andrew'
    dest_folder: '/var/www/html'

  tasks:
 
  - name: Check & print Linux version
    debug: var=ansible_os_family    

  - block: # FOR DEBIAN
      - name: apache apt Debian
        apt: name=apache2 state=latest update_cache=yes

      - name: start webserver
        service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"

  - block: # FOR RedHat
      - name: apache yum RedHat
        yum: name=httpd state=latest update_cache=yes

      - name: start webserver
        service: name=httpd state=started enabled=yes
    when: ansible_os_family == "RedHat"

  
  - name: copy homepage to server
    copy: src="{{ source_folder }}/{{ item }}" dest={{ dest_folder }} mode=0644
    loop: 
      - "index.html"
      - "hello.txt"
    notify:
      - restart apache Debian
      - restart httpd RedHat    
  
  
  
  handlers:
  - name: restart apache Debian
    service: name=apache2 state=restarted
    when: ansible_os_family == "Debian"

  - name: restart httpd RedHat
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"  
