---
- name: install default apache webserver
  hosts: prod
  become: true

  tasks:
  - name: install apache to prod server
    apt: name=apache2 state=present

  - name: enable on boot
    service: name=apache2 state=started enabled=yes




     
