---
- name: install apache &upload web page
  hosts: prod
  become: true

  vars:
    source_files: '/home/andrew/index.html'
    dest_files: '/var/www/html'

  tasks:
 
  - name: Check & print Linux version
    debug: var=ansible_os_family    

  - block: # FOR DEBIAN
      - name: apache apt Debian
        apt: name=apache2 state=latest
        update_cache: yes

      - name: copy homepage to server
        copy: src={{ source_files }} dest={{ dest_files }} mode=0644
        notify: restart apache Debian
        
      - name: start webserver
        service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"

  - block: # FOR RedHat
      - name: apache yum RedHat
        yum: name=httpd state=latest
        update-cache: yes

      - name: copy homepage to server
        copy: src={{ source_files }} dest={{ dest_files }} mode=0644
        notify: restart httpd RedHat
              
      - name: start webserver
        service: name=httpd state=started enabled=yes
    when: ansible_os_family == "RedHat"

  handlers:
  - name: restart apache Debian
    service: name=apache2 state=restarted

  - name: restart httpd RedHat
    service: name=httpd state=restarted  
