---
- name: install apache &upload web page
  hosts: prod
  become: true

  vars:
    source_files: '/home/andrew/index.html'
    dest_files: '/var/www/html'

  tasks:
  - name: Check & print Linux version
    

  - name: apache apt Debian
    apt: name=apache2 state=latest
    update-cache: yes
    when: ansible_os_family == "RedHat"

  - name: apache RedHat
    yum: name=httpd state=latest
    update-cache: yes
    when: ansible_os_family == "Debian"

  - name: copy homepage to server
    copy: src={{ source_files }} dest={{ dest_files }} mode=0644
    notify: restart apache

  - name: start webserver
    service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"

  - name: start webserver
    service: name=httpd state=started enabled=yes
    when: ansible_os_family == "RedHat"

  handlers:
  - name: restart apache Debian
    service: name=apache2 state=restarted

    handlers:
  - name: restart httpd RedHat
    service: name=apache2 state=restarted  
