---
- name: loops playbook
  hosts: prod
  become: true

  tasks:
  - name: hello 4 all Loop sample
    debug: msg="Hello {{ item }}"
    with_items: 
      - "Mens"
      - "Womens"
      - "Binary"
      - "NoSex"

  - name: Loop Until sample
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 3
    retries: 10
    until: output.stdout.find("ZZZZZ") == false

  - name: print final output
    debug: var=output.stdout


  