---
- name: Install nginx
  hosts: web
  become: true

  tasks:
  - name: Ensure nginx package is present
    apt:
     name: nginx
     state: present

  - name: Ensure index.html is present
    copy:
     src: index.html
     dest: /var/www/html

  - name: Ensure nginx service started
    service:
     name: nginx
     state: started


- name: Install db
  hosts: db
  become: true

  tasks:
  - name: Ensure postgresql package is present
    apt:
     name: postgresql
     state: present

  - name: Ensure postgresql service started
    service:
     name: postgresql
     state: started

