version: '3'
services:
  building:
    build:
      context: compile/
        volumes:
          - webapp_volume:/home/webapp/

#  prod:
#    build:
#      context: prod/
#        volumes:
#          - webapp_volume:/opt/tomcat/webapps

volumes:
  webapp_volume: