---
# tasks file for prod
- name: tomcat & openjdk-17-jre-headless must be
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "tomcat9"
    - "openjdk-11-jre-headless"

- name: start tomcat
  service: name="tomcat9" state=started    

- name: Copy war file to tomcat webapps directory
  copy:
    src: "{{ local_folder }}/hello-1.0.war"
    dest: "{{ tomcat_webapp_folder }}"
  notify:
    - restart tomcat

