---
# tasks file for deploy_apache
- name: Check & print Linux version
  debug: var=ansible_os_family    

- block: # FOR DEBIAN
    - name: apache apt Debian
      apt: name=apache2 state=latest update_cache=yes

    - name: start webserver
      service: name=apache2 state=started enabled=yes
  when: ansible_os_family == "Debian"

- block: # FOR RedHat
    - name: apache yum RedHat
      yum: name=httpd state=latest update_cache=yes

    - name: start webserver
      service: name=httpd state=started enabled=yes
  when: ansible_os_family == "RedHat"

- name: Generate html from j2
  template: src="index_adv.j2" dest="{{ dest_folder }}/index.html" mode=0555
  notify: 
    - restart apache Debian
    - restart httpd RedHat    
