pipeline {
    agent {
        docker { 
            image '51.250.101.254:8123/build_dind:v1.2'
            args '-u root -v /var/run/docker.sock:/var/run/docker.sock' 
            }
    }
    stages {
        stage('Clone git repo myboxfuse with Java project and Dockerfile for prod image') {
            steps {
                sh 'rm -rf myboxfuse'
                sh 'git clone https://github.com/tovmayor/myboxfuse.git'
            }
        }
        stage('Build jar') {
            steps {
                sh 'mvn -f ./myboxfuse package'
            }
        }
        stage('Make docker image') {
            steps {
                sh 'docker build -t 51.250.101.254:8123/prod_dind:v1.2 -f myboxfuse/DockerProd .'
                sh 'docker push 51.250.101.254:8123/prod_dind:v1.2'
                
            }
        }
    }
}