pipeline {
    agent none
    stages {
        stage ('Clone git repo, build war and prod docker image, push to nexus') {
            agent {
                docker { 
                    image '84.252.136.62:8123/build_dind:v1.2'
                    args '-u root -v /var/run/docker.sock:/var/run/docker.sock' 
                }
            }

            steps {
                sh 'rm -rf myboxfuse'
                sh 'git clone https://github.com/tovmayor/myboxfuse.git'
                sh 'mvn -f ./myboxfuse package'
                sh 'docker build -t 84.252.136.62:8123/prod_dind:v1.2 -f myboxfuse/DockerProd .'
                sh 'docker push 84.252.136.62:8123/prod_dind:v1.2'
                
            }
        }
        stage ('Run prod container') {
            agent any
            steps {
                sh '''ssh root@51.250.24.63 << EOF
                docker run -d 84.252.136.62:8123/prod_dind:v1.2
                EOF'''
            }
        }        
    }
}